[package]
name = "coldcard"
version = "0.5.0"
edition = "2021"
authors = ["Alfred Hodler <alfred_hodler@protonmail.com>"]
license = "MIT"
repository = "https://github.com/alfred-hodler/rust-coldcard/"
description = "Coldcard Wallet Interface Library in Rust"
keywords = ["coldcard", "bitcoin", "wallet"]
categories = ["command-line-utilities", "cryptography::cryptocurrencies", "hardware-support"]

[features]
default = ["linux-static-hidraw"]
linux-static-hidraw = ["hidapi/linux-static-hidraw"]
linux-static-libusb = ["hidapi/linux-static-libusb"]

[dependencies]
aes-ctr = "0.6.0"
bitcoin = { version = "0.29.1", features = ["rand"] }
hidapi = { version = "1.3.3", default-features = false }
log = { version = "0.4.17", optional = true }
